######################################################################
# Automatically generated by qmake (2.00a) Tue Sep 26 15:02:33 2006
######################################################################

TEMPLATE = app
TARGET = kreditrechner
QMAKE_CLEAN = kreditrechner
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
FORMS += dialog.ui
SOURCES += main.cpp dialog.cpp
